accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.main, name='main'),  
    path('login/kakao/', views.kakao_login, name='kakao-login'),
    path('login/kakao/callback/', views.kakao_login_callback, name='kakao-callback'),
    path('login/naver/', views.naver_login, name='naver-login'),
    path('login/naver/callback/', views.naver_login_callback, name='naver-callback'),
    path('login/naver/', views.naver_login, name='naver-login'),
    path('login/naver/callback/', views.naver_login_callback, name='naver-callback'),
    path('social_login', views.social_login, name="social_login"),
    path('start/', views.start, name='start'), 
    path('logout/', views.user_logout, name='logout'),
    path('mainpage/', views.main, name='mainpage'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('accounts:main'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),  # 소셜 로그인 부분 url (현재 임시)
    path('games/', include('games.urls')),
]

games/urls.py
from django.urls import path
from django.urls import path
from . import views
app_name = 'games'

urlpatterns = [
    path('', views.history_list, name='home'),  # 홈 페이지 -> 게임 히스토리 페이지
    path('history/', views.history_list, name='history_list'),  # 게임 히스토리 페이지
    path('attack/', views.attack, name='attack'),  # 공격 페이지
    path('rankings/', views.rankings, name='rankings'),  # 랭킹 보기

    # 다른 게임 관련 URL 추가 

    #게임 디테일
    path('game_detail/<int:game_id>/', views.game_detail, name='game_detail'), #게임상세페이지
    path('cancel/<int:game_id>/', views.cancel_game, name='cancel_game'), #게임취소처리
    path('counterAttack/<int:game_id>/', views.counter_attack, name='counter_attack'), #반격
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pirogrammer Card Game</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'rankings.css' %}">
    {% block head%}
    {% endblock %}
</head>
<body>
    <header>
        <a href="/" class="header-logo">Pirogrammer Card Game</a>
        <nav>
            {% if user.is_authenticated %}
                <a href="{% url 'games:attack'%}">게임하기</a>
                <a href="{% url 'games:history_list'%}">리스트 보기</a>
                <a href="{% url 'games:rankings' %}">랭킹보기</a>
                <a href="{% url 'accounts:logout' %}">로그아웃</a>
            {% else %}
                <a href="{% url 'accounts:social_login' %}">로그인</a>
                <a href="{% url 'accounts:social_login' %}">START</a>
            {% endif %}
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>피로그래밍 카드 게임 세션 2조</p>
    </footer>

    {% block scripts %}
    {% endblock %}
</body>
</html>